### Variables: r5.xlarge, 128, 128, 104857600, 8090, 8091, 7379, 2021-03-30T15:29:39.181559, m5.xlarge, 256

cluster_name: raysort-cluster
min_workers: 128
max_workers: 128

# The autoscaler will scale up the cluster faster with higher upscaling speed.
# E.g., if the task requires adding more nodes then autoscaler will gradually
# scale up the cluster in chunks of upscaling_speed*currently_running_nodes.
# This number should be > 0.
upscaling_speed: 1.0

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    use_internal_ip: yes

    # availability_zone: us-west-2a,us-west-2b

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu

# Provider-specific config for the head node.
head_node:
    InstanceType: r5.xlarge
    ImageId: ami-06515aeefbba7d475

# Provider-specific config for worker nodes.
worker_nodes:
    InstanceType: m5.xlarge
    ImageId: ami-06515aeefbba7d475
    BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
            VolumeSize: 256
    InstanceMarketOptions:
        MarketType: spot
    TagSpecifications:
      - ResourceType: instance
        Tags:
          - Key: Project
            Value: raysort
          - Key: RunId
            Value: "2021-03-30T15:29:39.181559"

# Specify the node type of the head node (as configured above).
head_node_type: head

# Specify the default type of the worker node (as configured above).
worker_default_node_type: worker

# Tell the autoscaler the allowed node types and the resources they provide.
# The key is the name of the node type, which is just for debugging purposes.
# The node config specifies the launch config and physical instance type.
available_node_types:
    head:
        node_config: {}
        resources: {"head": 1}

    worker:
        node_config: {}
        resources: {"worker:m5.xlarge": 1, "worker": 1}
        min_workers: 128
        max_workers: 128

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
#    "/path1/on/remote/machine": "/path1/on/local/machine",
    "/home/ubuntu/.aws/credentials": "/home/ubuntu/.aws/credentials",
    "/home/ubuntu/.netrc": "/home/ubuntu/.netrc",
    "/tmp/raysort": "/home/ubuntu/raysort",
}

# Files or directories to copy from the head node to the worker nodes. The format is a
# list of paths. The same path on the head node will be copied to the worker node.
# This behavior is a subset of the file_mounts behavior. In the vast majority of cases
# you should just use file_mounts. Only use this if you know what you're doing!
cluster_synced_files: []

# Whether changes to directories in file_mounts or cluster_synced_files in the head node
# should sync to the worker node continuously
file_mounts_sync_continuously: False

# Patterns for files to exclude when running rsync up or rsync down
rsync_exclude:
    - "**/.git"
    - "**/.git/**"

# Pattern files to use for filtering out files when running rsync up or rsync down. The file is searched for
# in the source directory and recursively through all subdirectories. For example, if .gitignore is provided
# as a value, the behavior will match git's behavior for finding and using .gitignore files.
rsync_filter:
    - ".rsyncignore"

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands: []

# List of shell commands to run to set up nodes.
setup_commands:
    # Note: if you're developing Ray, you probably want to create a Docker image that
    # has your Ray repo pre-cloned. Then, you can replace the pip installs
    # below with a git checkout <your_sha> (and possibly a recompile).
    # Uncomment the following line if you want to run the nightly version of ray (as opposed to the latest)
    # - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
    - conda activate base
    - cd /tmp/raysort && pip install -U -r requirements.txt && pip install -e .
    - cd /tmp/raysort/raysort/sortlib && python setup.py build_ext --inplace

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --head --port=6379 --object-manager-port=8076 --metrics-export-port=8090 --autoscaling-config=~/ray_bootstrap_config.yaml --num-cpus=0
    - /tmp/raysort/bin/prometheus/node_exporter --web.listen-address 0.0.0.0:8091 &
    - /tmp/raysort/bin/prometheus/prometheus --config.file=/tmp/raysort/config/prometheus.yml &
    - redis-server --port 7379 --protected-mode no --save '' &

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 --metrics-export-port=8090 --object-store-memory=104857600
    - /tmp/raysort/bin/prometheus/node_exporter --web.listen-address 0.0.0.0:8091 &
